// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ7rwf8-n0jpuFKtoi7qhNPjlpkWz-KSk',
    appId: '1:83543355758:web:638c237d15dfc17f1c117f',
    messagingSenderId: '83543355758',
    projectId: 'expense-tracker-f9756',
    authDomain: 'expense-tracker-f9756.firebaseapp.com',
    storageBucket: 'expense-tracker-f9756.firebasestorage.app',
    measurementId: 'G-6EDLJ9G1FT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXcyGn-WAKNhapLltqgByO8o8iZX8U2us',
    appId: '1:83543355758:android:8e278beadd49b14c1c117f',
    messagingSenderId: '83543355758',
    projectId: 'expense-tracker-f9756',
    storageBucket: 'expense-tracker-f9756.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVdZ4tJWmjqCK5hBKMbOaxQyyopge6hWY',
    appId: '1:83543355758:ios:661366619ffdc3bf1c117f',
    messagingSenderId: '83543355758',
    projectId: 'expense-tracker-f9756',
    storageBucket: 'expense-tracker-f9756.firebasestorage.app',
    androidClientId: '83543355758-nu04a39lkvsjniggkrvaae839edb9g5d.apps.googleusercontent.com',
    iosClientId: '83543355758-344ijlvq8f650mmpqfu7hgf7ih7aan65.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTracker',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVdZ4tJWmjqCK5hBKMbOaxQyyopge6hWY',
    appId: '1:83543355758:ios:661366619ffdc3bf1c117f',
    messagingSenderId: '83543355758',
    projectId: 'expense-tracker-f9756',
    storageBucket: 'expense-tracker-f9756.firebasestorage.app',
    androidClientId: '83543355758-nu04a39lkvsjniggkrvaae839edb9g5d.apps.googleusercontent.com',
    iosClientId: '83543355758-344ijlvq8f650mmpqfu7hgf7ih7aan65.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ7rwf8-n0jpuFKtoi7qhNPjlpkWz-KSk',
    appId: '1:83543355758:web:1e973eed857c99df1c117f',
    messagingSenderId: '83543355758',
    projectId: 'expense-tracker-f9756',
    authDomain: 'expense-tracker-f9756.firebaseapp.com',
    storageBucket: 'expense-tracker-f9756.firebasestorage.app',
    measurementId: 'G-H0D3E949Y5',
  );
}
