import 'package:cloud_firestore/cloud_firestore.dart';

import '../models/expense.dart';

/// Owns all Firestore read/write operations for expenses.
///
/// Collection path: `users/{uid}/expenses/{expenseId}`
///
/// ViewModels receive this repository through constructor injection.
/// Widgets must never call this class directly.
///
/// For testing, inject a [FakeFirebaseFirestore] or replace this class
/// with a fake that returns canned data.
class ExpenseRepository {
  ExpenseRepository({FirebaseFirestore? firestore})
    : _injectedFirestore = firestore;

  final FirebaseFirestore? _injectedFirestore;
  FirebaseFirestore get _firestore => _injectedFirestore ?? FirebaseFirestore.instance;

  /// Returns a reference to the expenses subcollection for [userId].
  CollectionReference<Map<String, dynamic>> _expensesCollection(String userId) {
    return _firestore.collection('users').doc(userId).collection('expenses');
  }

  /// Watches all expenses for [userId], ordered by date descending.
  ///
  /// Emits a new list whenever the Firestore collection changes.
  /// Malformed documents are silently skipped.
  Stream<List<Expense>> watchExpenses(String userId) {
    return _expensesCollection(userId)
        .orderBy('date', descending: true)
        .snapshots()
        .map((snapshot) {
          return snapshot.docs
              .map(Expense.fromFirestore)
              .whereType<Expense>()
              .toList();
        });
  }

  /// Creates a new expense document. The ID is auto-generated by Firestore.
  Future<String> addExpense(String userId, Expense expense) async {
    final docRef = await _expensesCollection(userId)
        .add(expense.toFirestore(isNew: true));
    return docRef.id;
  }

  /// Updates an existing expense document identified by [expense.id].
  Future<void> updateExpense(String userId, Expense expense) async {
    await _expensesCollection(userId)
        .doc(expense.id)
        .update(expense.toFirestore());
  }

  /// Deletes the expense document with [expenseId].
  Future<void> deleteExpense(String userId, String expenseId) async {
    await _expensesCollection(userId).doc(expenseId).delete();
  }
}
